### ISSUE TITLE
Difficulty using abracad.avro with string field

### ISSUE THREAD

**Issue by tewarfel** [damballa/abracad#19] opened 2015-09-22 00:55 UTC
I'm trying to write an Avro JSON encoding with a simple JSON schema, 

```clojure
(ns foo.core
  (:require [abracad.avro :as avro])
  (:gen-class))

(defn encode-session-request [session-name ]
   (let [schema (avro/parse-schema
                     {:type "record",
                      :name "SessionRequest",
                      :fields [{:name "sessionID", :type :string}
                               {:name "someNumber", :type :long }]})
        avro-request (avro/json-encoded schema session-name 42)]
       avro-request))

(defn -main [ ]
   (println (encode-session-request "aSessionName")))
```
but am getting the compile-time error

_Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :field-list of protocol: #'abracad.avro/AvroSerializable found for class: java.lang.String, compiling:(/private/var/folders/p6/ynk66dwn3yndyx3fv787ysd4rvtp8r/T/form-init2135414968022195924.clj:1:125)_

Am I missing something?

Thanks,
-Tom

**Comment by llasram** [comment] 2015-09-22 00:58
Answered via e-mail.  Doesn't seem to be a bug, so closing this issue for now, but feel free to re-open if I missed something.

**Closed by llasram** 2015-09-22 00:58 UTC

**Comment by gareth625** [comment] 2016-11-17 08:30
I'm also struggling with this problem when trying to Avro as a serialization format with Parkour. Where should I be looking for the answer?

**Comment by gareth625** [comment] 2016-11-17 10:21
This was, as I was expecting based on the comments above, a user error or my fault to put it another way ;)

I ended up with a mismatch with the data I was trying to write and the schema I said it matched. I don't know how/why it gave me that error, but it was a symptom of a data/schema mismatch.

**Comment by llasram** [comment] 2016-11-17 11:31
I'm glad you figured it out -- the e-mailed request and reply to the original issue were left behind in the e-mail account of my previous job. With your diagnosis jogging my memory, I believe that particular error is caused by the serialization plumbing expecting a map to encode as a record, but instead encountering a string.  Hopefully this comment will help anyone who runs into this issue in the future.
